from collections.abc import Callable

from .core.instance import RazTint as RazTint
from .data import INTENTS as INTENTS
from .data import IntentConfig as IntentConfig
from .data.types import (
    BackgroundColorName,
    ColorName,
    IconMode,
    IntentName,
    StyleName,
)
from .formatting.paint import UNSET, IconArg
from .security import DEFAULT_RULES as DEFAULT_RULES
from .security import MaskRule as MaskRule

__version__: str

tint: RazTint

_IconFn = Callable[[], str]
_TextFn = Callable[[str], str]

def ok() -> str: ...
def err() -> str: ...
def warn() -> str: ...
def info() -> str: ...
def black(text: str) -> str: ...
def red(text: str) -> str: ...
def green(text: str) -> str: ...
def yellow(text: str) -> str: ...
def blue(text: str) -> str: ...
def magenta(text: str) -> str: ...
def cyan(text: str) -> str: ...
def white(text: str) -> str: ...
def gray(text: str) -> str: ...
def bright_red(text: str) -> str: ...
def bright_green(text: str) -> str: ...
def bright_yellow(text: str) -> str: ...
def bright_blue(text: str) -> str: ...
def bright_magenta(text: str) -> str: ...
def bright_cyan(text: str) -> str: ...
def bright_white(text: str) -> str: ...
def bg_black(text: str) -> str: ...
def bg_red(text: str) -> str: ...
def bg_green(text: str) -> str: ...
def bg_yellow(text: str) -> str: ...
def bg_blue(text: str) -> str: ...
def bg_magenta(text: str) -> str: ...
def bg_cyan(text: str) -> str: ...
def bg_white(text: str) -> str: ...
def bg_gray(text: str) -> str: ...
def bg_bright_red(text: str) -> str: ...
def bg_bright_green(text: str) -> str: ...
def bg_bright_yellow(text: str) -> str: ...
def bg_bright_blue(text: str) -> str: ...
def bg_bright_magenta(text: str) -> str: ...
def bg_bright_cyan(text: str) -> str: ...
def bg_bright_white(text: str) -> str: ...
def bold(text: str) -> str: ...
def dim(text: str) -> str: ...
def italic(text: str) -> str: ...
def underline(text: str) -> str: ...
def strikethrough(text: str) -> str: ...
def redact(
    text: str,
    rules: tuple[MaskRule, ...] | list[MaskRule] | None = None,
) -> str: ...
def paint(
    text: str,
    color: ColorName | int | None = None,
    bg: BackgroundColorName | int | None = None,
    styles: StyleName | list[StyleName] | None = None,
    reset: bool = True,
    icon: IconArg = UNSET,
    icon_mode: IconMode | None = None,
    redact: bool = False,
    redact_rules: list[MaskRule] | None = None,
    intent: IntentName | None = None,
) -> str: ...

__all__: list[str]

def rgb(text: str, r: int, g: int, b: int) -> str: ...
def bg_rgb(text: str, r: int, g: int, b: int) -> str: ...
def hex_color(text: str, hex_str: str) -> str: ...
def bg_hex_color(text: str, hex_str: str) -> str: ...
def color256(text: str, index: int) -> str: ...
def bg_color256(text: str, index: int) -> str: ...
