name: Bug Report
description: Report a reproducible bug or issue with RazTint.
title: "[BUG] Short Description of the Issue"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please fill out the details below.

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: What steps did you take to encounter the bug?
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? (Include screenshots or terminal output if possible)
    validations:
      required: true

  - type: input
    id: raztint-version
    attributes:
      label: RazTint Version
      description: What version of the library are you using (e.g., 0.1.0)?

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux (Specify Distribution)
        - Other (Specify in details)
    validations:
      required: true

  - type: input
    id: terminal-app
    attributes:
      label: Terminal Application
      description: Which terminal are you using (e.g., Windows Terminal, iTerm2, VS Code Integrated)?

  - type: dropdown
    id: nerd-font
    attributes:
      label: Nerd Font Status
      description: Is a Nerd Font installed and configured in your terminal?
      options:
        - 'Yes, fully installed'
        - 'No'
        - 'Unsure'
    validations:
      required: true